### ISSUE TITLE
Use Int for ID instead of string

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGizmos/Observables.jl#18]
https://github.com/JuliaGizmos/Observables.jl/blob/40243b2b8c7970ab5445d6d58d29f65a749abbf2/src/Observables.jl#L20
Should give quite a speed up compared to a string field - also it will be much clearer that it's an ID.
I also don't like to mix names and ids like this. It should either be a name or a unique id in my book ;)
We could have something like this, to have the best of both worlds:
```Julia
const name_dict = Dict{Int, String}()
Observable(x, name = nothing) = (...; name != nothing && name_dict[id] = name)
name(x::Observable) = get(name_dict, x.id) do 
    error("Observable doesn't have a name. You may call it numer: $(x.id), though")
end
```
Could do a PR if this is appreciated

**Comment by SimonDanisch** [comment]
Should I go ahead and implement this?

**Comment by travigd** [comment]
I believe that you did this in #40. :^)
