### ISSUE TITLE
Use |> operator!

### ISSUE THREAD

**Issue by yuehhua** [JuliaGizmos/Observables.jl#3]
I'm very excited to see this project!

Previously, I tried to implement Rx in julia. Then, I change my mind to implement additional functionality to Reactive.jl.

I plan to leverage the |> operator

```
result = from([1,2,3,4,5])
         |> map(x -> x + 1)
         |> subscribe()
``` 

but I'm busy recently...

**Comment by yuehhua** [comment]
OK~~It seems that someone had got this done.
[Lazy.jl](https://github.com/MikeInnes/Lazy.jl)

**Comment by shashi** [comment]
Thanks @yuehhua! Nice to see your interest in this repo!

I haven't yet planned for this project to be as expansive as Rx (which I only know probably 10% of). I'm happy for now to have a type which lets me watch for changes to a value while allowing highest flexibility in how these objects can be programmed to work together.
